name: CI - Build Python Package

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build Python Package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3 libraries
        run: pip3 install setuptools wheel

      - name: Validate Library
        run: python3 py_sip_xnu.py

      - name: Build Package
        run: python3 setup.py bdist_wheel --universal
      - name: Test Package
        run: python3 setup.py test

      - name: Upload Wheel Package
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist


